import tp
import mm


def init():
    x = tp.Tp("sea1")
    x.set_short_name("sea")
    x.set_is_sea(True)
    x.set_world_depth("sea")
    x.set_is_animated(True)
    x.set_scale(1*0.25)

    mm.tp_set_tile(x, tile="sea1.1", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.2", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.3", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.4", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.5", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.6", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.7", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.8", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.9", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.10", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.11", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.12", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.13", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.14", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.15", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.16", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.17", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.18", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.19", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.20", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.21", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.22", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.23", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.24", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.25", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.26", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.27", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.28", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.29", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.30", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.31", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.32", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.33", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.34", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.35", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.36", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.37", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.38", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.39", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.40", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.41", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.42", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.43", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.44", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.45", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.46", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.47", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.48", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.49", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.50", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.51", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.52", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.53", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.54", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.55", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.56", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.57", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.58", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.59", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.60", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.61", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.62", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.63", delay_ms=50)
    mm.tp_set_tile(x, tile="sea1.64", delay_ms=50)

init()
