import tp
import mm

def thing_init(t):
    t.set_description("A weapon")

def weapon_init(name, short_name):
    x = tp.Tp(name)
    x.set_short_name(short_name)
    x.set_is_weapon(True)
    x.set_world_depth("player")

    x.set_tile(tile=name)
    x.thing_init = thing_init

def init():
    weapon_init(name="axe1.1",             short_name="Hand-axe")
    weapon_init(name="axe1.2",             short_name="Battle-axe")
    weapon_init(name="axe1.3",             short_name="Great-axe")
    weapon_init(name="axe1.4",             short_name="Master-axe")
    weapon_init(name="axe1.5",             short_name="Golden-axe")
    weapon_init(name="axe1.6",             short_name="Diamond-axe")
    weapon_init(name="axe1.7",             short_name="Blood-axe")
    weapon_init(name="axe1.9",             short_name="Cleaver-axe")
    weapon_init(name="ball_chain1.1",      short_name="Flail")
    weapon_init(name="ball_chain1.2",      short_name="Golden flail")
    weapon_init(name="ball_chain1.3",      short_name="Diamond flail")
    weapon_init(name="bow1.1",             short_name="Bow")
    weapon_init(name="bow1.2",             short_name="Longbow")
    weapon_init(name="bow1.3",             short_name="Metal bow")
    weapon_init(name="bow1.4",             short_name="Platinum bow")
    weapon_init(name="bow1.5",             short_name="Golden bow")
    weapon_init(name="bow1.6",             short_name="Crossbow")
    weapon_init(name="bow1.7",             short_name="Metal crossbow")
    weapon_init(name="bow1.8",             short_name="Golden crossbow")
    weapon_init(name="mace1.1",            short_name="Mace")
    weapon_init(name="mace1.2",            short_name="War mace")
    weapon_init(name="quiver1.1",          short_name="Arrows")
    weapon_init(name="quiver1.2",          short_name="Flame arrows")
    weapon_init(name="quiver1.3",          short_name="Energy arrows")
    weapon_init(name="quiver1.4",          short_name="Acid arrows")
    weapon_init(name="stick1.1",           short_name="Stick")
    weapon_init(name="stick1.2",           short_name="Flame stick")
    weapon_init(name="stick1.3",           short_name="Magic stick")
    weapon_init(name="stick2.1",           short_name="Stick V2")
    weapon_init(name="stick2.2",           short_name="Hooked stick")
    weapon_init(name="stick2.3",           short_name="Gnarly stick")
    weapon_init(name="stick2.4",           short_name="Battle stick")
    weapon_init(name="sword1.1",           short_name="Shortest sword")
    weapon_init(name="sword1.2",           short_name="Short sword")
    weapon_init(name="sword1.3",           short_name="Needle sword")
    weapon_init(name="sword1.4",           short_name="Meat cleaver")
    weapon_init(name="sword1.5",           short_name="Ice shortsword")
    weapon_init(name="sword1.6",           short_name="Platinum shortsword")
    weapon_init(name="sword1.7",           short_name="Flaming shortsword")
    weapon_init(name="sword1.8",           short_name="Gladius")
    weapon_init(name="sword1.9",           short_name="Dao")
    weapon_init(name="sword1.10",          short_name="Khopesh")
    weapon_init(name="sword1.11",          short_name="Long sword")
    weapon_init(name="sword1.12",          short_name="Claymore")
    weapon_init(name="sword1.13",          short_name="Greatsword")
    weapon_init(name="sword1.14",          short_name="Golden greatsword")
    weapon_init(name="sword1.15",          short_name="Platinum greatsword")
    weapon_init(name="sword1.16",          short_name="Flaimin greatsword")
    weapon_init(name="sword1.17",          short_name="Serrated sword")
    weapon_init(name="sword1.18",          short_name="Ulfbehrt")
    weapon_init(name="sword1.19",          short_name="Khanda")
    weapon_init(name="sword1.20",          short_name="Ice sword")
    weapon_init(name="sword1.22",          short_name="Zweihande")
    weapon_init(name="sword_wooden1.1",    short_name="Wood sword")
    weapon_init(name="warhammer1.1",       short_name="Maul")
    weapon_init(name="warhammer1.2",       short_name="Warhammer")
    weapon_init(name="warhammer1.3",       short_name="Golden warhammer")

init()
