import tp
import mm

def thing_init(t):
    t.set_description("A weapon")

def weapon_init(name, short_name):
    x = tp.Tp(name)
    x.set_short_name(short_name)
    x.set_is_weapon(True)
    x.set_world_depth("player")

    x.set_tile(tile=name)
    x.thing_init = thing_init

def init():
    weapon_init(name="axe1.1",             short_name="Hand Axe")
    weapon_init(name="axe1.2",             short_name="Battle Axe")
    weapon_init(name="axe1.3",             short_name="Greataxe")
    weapon_init(name="axe1.4",             short_name="Even Greater Axe")
    weapon_init(name="axe1.5",             short_name="Golden Axe")
    weapon_init(name="axe1.6",             short_name="Diamond Axe")
    weapon_init(name="axe1.7",             short_name="Blood Axe")
    weapon_init(name="axe1.9",             short_name="Cleaver Axe")
    weapon_init(name="ball_chain1.1",      short_name="Flail")
    weapon_init(name="ball_chain1.2",      short_name="Golden Flail")
    weapon_init(name="ball_chain1.3",      short_name="Diamond Flail")
    weapon_init(name="bow1.1",             short_name="Bow")
    weapon_init(name="bow1.2",             short_name="Longishbow")
    weapon_init(name="bow1.3",             short_name="Metal Longbow")
    weapon_init(name="bow1.4",             short_name="Bowmaster")
    weapon_init(name="bow1.5",             short_name="Golden Bow")
    weapon_init(name="bow1.6",             short_name="Crossbow")
    weapon_init(name="bow1.7",             short_name="Metal cross")
    weapon_init(name="bow1.8",             short_name="Golden cross")
    weapon_init(name="mace1.1",            short_name="Mace")
    weapon_init(name="mace1.2",            short_name="War Mace")
    weapon_init(name="quiver1.1",          short_name="Arrows")
    weapon_init(name="quiver1.2",          short_name="Flame Arrows")
    weapon_init(name="quiver1.3",          short_name="Energy Arrows")
    weapon_init(name="quiver1.4",          short_name="Acid Arrows")
    weapon_init(name="stick1.1",           short_name="Just a stick")
    weapon_init(name="stick1.2",           short_name="Flame Stick")
    weapon_init(name="stick1.3",           short_name="Magic Stick")
    weapon_init(name="stick2.1",           short_name="Stick V2")
    weapon_init(name="stick2.2",           short_name="Hooked Stick")
    weapon_init(name="stick2.3",           short_name="Gnarly Stick")
    weapon_init(name="stick2.4",           short_name="Battle Stick")
    weapon_init(name="sword1.1",           short_name="Shortest Sword")
    weapon_init(name="sword1.2",           short_name="Short Sword")
    weapon_init(name="sword1.3",           short_name="Needle Sword")
    weapon_init(name="sword1.4",           short_name="Meat Cleaver")
    weapon_init(name="sword1.5",           short_name="Ice Shortsword")
    weapon_init(name="sword1.6",           short_name="Platinum Shortsword")
    weapon_init(name="sword1.7",           short_name="Flaming Shortsword")
    weapon_init(name="sword1.8",           short_name="Gladius")
    weapon_init(name="sword1.9",           short_name="Dao")
    weapon_init(name="sword1.10",          short_name="Khopesh")
    weapon_init(name="sword1.11",          short_name="Long Sword")
    weapon_init(name="sword1.12",          short_name="Claymore")
    weapon_init(name="sword1.13",          short_name="Greatsword")
    weapon_init(name="sword1.14",          short_name="Golden Greatsword")
    weapon_init(name="sword1.15",          short_name="Platinum Greatsword")
    weapon_init(name="sword1.16",          short_name="Flaimin Greatsword")
    weapon_init(name="sword1.17",          short_name="Serrated Sword")
    weapon_init(name="sword1.18",          short_name="Ulfbehrt")
    weapon_init(name="sword1.19",          short_name="Khanda")
    weapon_init(name="sword1.20",          short_name="Ice Sword")
    weapon_init(name="sword1.22",          short_name="Zweihande")
    weapon_init(name="sword_wooden1.1",    short_name="Wooden Sword aka Stick")
    weapon_init(name="warhammer1.1",       short_name="Maul")
    weapon_init(name="warhammer1.2",       short_name="Warhammer")
    weapon_init(name="warhammer1.3",       short_name="Golden Warhammer")

init()
