/*
 * Copyright (C) 2011-2017 goblinhack@gmail.com
 *
 * See the README file for license info.
 */

#pragma once

#include <Python.h>

PyObject *tp_load_(PyObject *obj, PyObject *args, PyObject *keywds);

#define TP_SET_PROTO(__field__)                                                     \
PyObject *tp_set_ ## __field__ (PyObject *obj, PyObject *args, PyObject *keywds);

#define TP_SET_DECL(__field__)                                                      \
    {"tp_set_" #__field__,                                                      \
        (PyCFunction)tp_set_ ## __field__,                                      \
        METH_VARARGS | METH_KEYWORDS,                                           \
        "set a " #__field__ " in a thing template"},                            \

TP_SET_PROTO(tile)
TP_SET_PROTO(light_radius)
TP_SET_PROTO(scale)
TP_SET_PROTO(z_depth)
TP_SET_PROTO(z_order)
TP_SET_PROTO(z_depth)
TP_SET_PROTO(speed)
TP_SET_PROTO(blit_top_off)
TP_SET_PROTO(blit_bot_off)
TP_SET_PROTO(blit_left_off)
TP_SET_PROTO(blit_right_off)
TP_SET_PROTO(short_name)
TP_SET_PROTO(raw_name)
TP_SET_PROTO(light_tint)
TP_SET_PROTO(is_animated)
TP_SET_PROTO(is_animated_no_dir)
TP_SET_PROTO(is_animation)
TP_SET_PROTO(is_candle_light)
TP_SET_PROTO(is_cats_eyes)
TP_SET_PROTO(is_shadow_caster)
TP_SET_PROTO(is_shadow_caster_soft)
TP_SET_PROTO(is_door)
TP_SET_PROTO(is_water)
TP_SET_PROTO(is_lava)
TP_SET_PROTO(is_effect_fade_in_out)
TP_SET_PROTO(is_effect_pulse)
TP_SET_PROTO(is_effect_rotate_2way)
TP_SET_PROTO(is_effect_sway)
TP_SET_PROTO(is_explosion)
TP_SET_PROTO(is_food)
TP_SET_PROTO(is_weapon)
TP_SET_PROTO(is_hidden)
TP_SET_PROTO(is_monst)
TP_SET_PROTO(is_player)
TP_SET_PROTO(is_rock)
TP_SET_PROTO(is_rrr1)
TP_SET_PROTO(is_rrr2)
TP_SET_PROTO(is_rrr3)
TP_SET_PROTO(is_rrr4)
TP_SET_PROTO(is_rrr5)
TP_SET_PROTO(is_rrr6)
TP_SET_PROTO(is_rrr7)
TP_SET_PROTO(is_rrr8)
TP_SET_PROTO(is_rrr9)
TP_SET_PROTO(is_rrr10)
TP_SET_PROTO(is_rrr11)
TP_SET_PROTO(is_rrr12)
TP_SET_PROTO(is_rrr13)
TP_SET_PROTO(is_rrr14)
TP_SET_PROTO(is_rrr15)
TP_SET_PROTO(is_rrr16)
TP_SET_PROTO(is_rrr17)
TP_SET_PROTO(is_rrr18)
TP_SET_PROTO(is_rrr19)
TP_SET_PROTO(is_rrr20)
TP_SET_PROTO(is_rrr21)
TP_SET_PROTO(is_rrr22)
TP_SET_PROTO(is_rrr23)
TP_SET_PROTO(is_rrr24)
TP_SET_PROTO(is_rrr25)
TP_SET_PROTO(is_rrr26)
TP_SET_PROTO(is_rrr27)
TP_SET_PROTO(is_rrr28)
TP_SET_PROTO(is_rrr29)
TP_SET_PROTO(is_rrr30)
TP_SET_PROTO(is_rrr31)
TP_SET_PROTO(is_rrr32)
TP_SET_PROTO(is_rrr33)
TP_SET_PROTO(is_rrr34)
TP_SET_PROTO(is_rrr35)
TP_SET_PROTO(is_rrr36)
TP_SET_PROTO(is_rrr37)
TP_SET_PROTO(is_rrr38)
TP_SET_PROTO(is_rrr39)
TP_SET_PROTO(is_rrr40)
TP_SET_PROTO(is_rrr41)
TP_SET_PROTO(is_rrr42)
TP_SET_PROTO(is_rrr43)
TP_SET_PROTO(is_rrr44)
TP_SET_PROTO(is_rrr45)
TP_SET_PROTO(is_rrr46)
TP_SET_PROTO(has_shadow)
TP_SET_PROTO(is_chair)
TP_SET_PROTO(is_chest)
TP_SET_PROTO(is_bookcase)
TP_SET_PROTO(is_table)
TP_SET_PROTO(is_lawn)
TP_SET_PROTO(is_carpet_deco)
TP_SET_PROTO(is_carpet)
TP_SET_PROTO(is_house_item)
TP_SET_PROTO(is_cwall)
TP_SET_PROTO(is_animated_lr_flip)
TP_SET_PROTO(is_gravel_snow_deco)
TP_SET_PROTO(is_landrock_snow)
TP_SET_PROTO(is_hidden_from_editor)
TP_SET_PROTO(is_hwall)
TP_SET_PROTO(is_dungeon_item)
TP_SET_PROTO(is_difficulty_easy)
TP_SET_PROTO(is_difficulty_hard)
TP_SET_PROTO(is_difficulty_nightmare)
TP_SET_PROTO(is_world_item)
TP_SET_PROTO(is_solid_ground)
TP_SET_PROTO(is_dungeon_way_up)
TP_SET_PROTO(is_dirt_deco)
TP_SET_PROTO(is_dirt_snow_deco)
TP_SET_PROTO(is_grass_deco)
TP_SET_PROTO(is_grass_snow_deco)
TP_SET_PROTO(is_gravel_deco)
TP_SET_PROTO(is_sand_deco)
TP_SET_PROTO(is_sand_snow_deco)
TP_SET_PROTO(is_snow_deco)
TP_SET_PROTO(is_sand_snow)
TP_SET_PROTO(is_dirt_snow)
TP_SET_PROTO(is_grass_snow)
TP_SET_PROTO(is_road_snow)
TP_SET_PROTO(is_road)
TP_SET_PROTO(is_dungeon_snow)
TP_SET_PROTO(is_dungeon)
TP_SET_PROTO(is_focus)
TP_SET_PROTO(is_gravel_snow)
TP_SET_PROTO(is_tree_conifer)
TP_SET_PROTO(is_snow_mound)
TP_SET_PROTO(is_rock)
TP_SET_PROTO(is_ice)
TP_SET_PROTO(is_ice)
TP_SET_PROTO(is_gravel)
TP_SET_PROTO(is_small_rock)
TP_SET_PROTO(is_marsh_plant)
TP_SET_PROTO(is_landrock)
TP_SET_PROTO(is_snow)
TP_SET_PROTO(is_hidden)
TP_SET_PROTO(is_dirt)
TP_SET_PROTO(is_sand)
TP_SET_PROTO(is_plant)
TP_SET_PROTO(is_tree)
TP_SET_PROTO(is_grass)
TP_SET_PROTO(is_bridge)
TP_SET_PROTO(is_movement_blocking)
TP_SET_PROTO(is_treasure)
TP_SET_PROTO(is_dungeon_way_up)
TP_SET_PROTO(is_dungeon_way_down)
TP_SET_PROTO(is_chasm_smoke)
TP_SET_PROTO(is_key)
TP_SET_PROTO(is_dusty)
TP_SET_PROTO(is_corridor)
TP_SET_PROTO(light_pulse_amount)
TP_SET_PROTO(is_healing)
TP_SET_PROTO(is_armor)
TP_SET_PROTO(is_magical)
TP_SET_PROTO(is_shadow_caster)
TP_SET_PROTO(is_shadow_caster_soft)
TP_SET_PROTO(is_sleeping)
TP_SET_PROTO(is_wall)
TP_SET_PROTO(is_door)
TP_SET_PROTO(is_water)
TP_SET_PROTO(is_lava)
TP_SET_PROTO(is_floor)
